Update rules.bolt
Verdagon/ghvz pull request #146
Opened 2017-06-26 18:28 UTC by stealthflyer

Based on the latest sample data to include notifications, maps, markers, and lives

2017-06-26 20:32 UTC, Verdagon requested changes

2017-06-26 20:32 UTC, Verdagon commented on firebase/rules.bolt
> +  ('privateLife-' + auth.uid)
alas, we cant make this assumption =(

a player might go through multiple lives throughout the game, and each one will have a different ID, and a different code.

2017-06-26 20:32 UTC, Verdagon commented on firebase/rules.bolt
> +  chatRoomMemberships: Map<ChatRoomId, ChatRoomLookup>;
can we call this ChatRoomLookup a ChatRoomMembership? thanks!

2017-06-26 20:32 UTC, Verdagon commented on firebase/rules.bolt
> -  lives: Map<LifeId, PublicLife>
accidental? there should still be a lives in publicplayer

2017-06-26 20:32 UTC, Verdagon commented on firebase/rules.bolt
>  /playersPrivate/{PlayerId} is PrivatePlayer;
in the firebase, this was renamed to privatePlayers and publicPlayers (to be consistently the same name as their type)

2017-06-26 20:38 UTC, Verdagon commented
also, can you see if backend_test runs well with these in place? thanks!

2017-06-26 21:48 UTC, stealthflyer commented
Made the changes. Backend test run fine, but they are the server and thus it will work. Front end looks fine too (seems odd, maybe my config isn't running?)

2017-06-27 05:08 UTC, Verdagon approved these changes

2017-06-27 05:08 UTC, merged